### ISSUE TITLE
lolcat and non ASCII chars

### ISSUE THREAD

**Issue by musclorr** [tehmaze/lolcat#3]
lolcat does not work with UTF-8 characters and Python 2

lolcat works with UTF-8 characters in Python 3, but unfortunately Python 3 breaks the animation.

EDIT: lolcat file does not work as well with Python 3

**Comment by swordfeng** [comment]
If you change 'xrange' to 'range', and run it with py3, then it works well.

**Comment by tehmaze** [comment]
Version 0.43.0 was released, fixing both issues (now also works in Python 3).
