### ISSUE TITLE
How can i used it with  "top" command

### ISSUE THREAD

**Issue by nicolabortignon** [tehmaze/lolcat#5]
Maybe a really newbie question, but if I type 

top -u -s 10 | lolcat 

it doesn't work.

**Comment by fredrikmollerstrand** [comment]
`top` enters "interactive" mode by default, as opposed to printing on stdout once and exiting.

You can do this on Linux:

`top -n 1 | lolcat`

and this on OS X:

`top -l 1 | lolcat`

**Comment by tehmaze** [comment]
top(1) by default also uses ANSI SGR, you can run:

    $ TERM=dumb top -n 1 | lolcat

And it will work as expected. If you want "continuous top", you can so something like:

    $ while :; do echo -en "\e[2J"; do TERM=dumb top -n 1 | head -n $LINES | lolcat; sleep 1; done

Warning, the command above is Linux-only and non-portable :-)

**Comment by fredrikmollerstrand** [comment]
`while :;` and then clearing the screen with `"\e[2J"` is cute, can't believe I haven't come across that before
